//! Turns a results file into the tables that get published.
//!
//! Generated, never hand-maintained: `BENCHMARKS.md` and any comparison table come from
//! here, so a number cannot reach a reader without the definition, sample count and
//! evidence grade that make it readable. Editing the markdown by hand is how a table
//! outlives the run that produced it and becomes a claim nobody can reproduce.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use anyhow::Result;

use crate::schema::{Datapoint, Probe, Run};

/// One table per probe, rows grouped by class. A row that cannot be compared is moved
/// below the table with its reason rather than dropped, because a silently missing
/// competitor reads as a result.
pub fn markdown(run: &Run) -> Result<String> {
    let mut out = String::new();
    writeln!(
        out,
        "<!-- generated by brain-bench; edits here are overwritten -->"
    )?;
    writeln!(out, "# Benchmark results\n")?;
    writeln!(out, "Run `{}` on {}.\n", run.run_id, describe_host(run))?;

    if run.outcome != crate::schema::Outcome::Complete {
        writeln!(
            out,
            "> [!WARNING]\n> This run ended as **{:?}** — spot capacity was reclaimed, or the \
             wall-clock budget ran out. Probes that never ran are absent, not zero.\n",
            run.outcome
        )?;
    }

    let mut by_probe: BTreeMap<Probe, Vec<&Datapoint>> = BTreeMap::new();
    for point in &run.datapoints {
        by_probe.entry(point.probe).or_default().push(point);
    }

    for (probe, points) in &by_probe {
        writeln!(out, "## {}\n", probe.as_str())?;
        writeln!(
            out,
            "| Subject | Value | p50 | p99 | n | What it measures |"
        )?;
        writeln!(out, "| --- | ---: | ---: | ---: | ---: | --- |")?;

        let mut withheld = Vec::new();
        for point in points {
            match point.comparable() {
                Ok(()) => writeln!(
                    out,
                    "| {} | {:.3} {} | {} | {} | {} | {} |",
                    point.subject,
                    point.value,
                    point.unit,
                    optional(point.percentiles.p50_ms),
                    optional(point.percentiles.p99_ms),
                    point.n,
                    point.definition
                )?,
                Err(reason) => withheld.push((point, reason)),
            }
        }

        if !withheld.is_empty() {
            writeln!(out, "\n**Withheld from the table above:**\n")?;
            for (point, reason) in withheld {
                writeln!(
                    out,
                    "- `{}` — {:.3} {} — {reason}.",
                    point.subject, point.value, point.unit
                )?;
            }
        }
        writeln!(out)?;
        memory(&mut out, points)?;
    }

    if !run.skipped.is_empty() {
        writeln!(out, "## Not measured\n")?;
        for skip in &run.skipped {
            writeln!(
                out,
                "- `{}` / {} — {}",
                skip.subject,
                skip.probe.as_str(),
                skip.reason
            )?;
        }
        writeln!(out)?;
    }
    Ok(out)
}

/// Memory recorded during a probe: the fit where sessions were ramped, and the shape of
/// the series otherwise.
///
/// Every probe carries a series, so "memory under load" is read off the throughput probe
/// and "memory over time" off any probe's own tail — the same readings, asked different
/// questions.
fn memory(out: &mut String, points: &[&Datapoint]) -> Result<()> {
    let with_memory: Vec<&&Datapoint> = points
        .iter()
        .filter(|point| !point.memory_kib.is_empty())
        .collect();
    if with_memory.is_empty() {
        return Ok(());
    }

    writeln!(out, "### Private memory during this probe\n")?;
    writeln!(
        out,
        "| Subject | Start | Peak | End | Per session | Linear fit | Readings |"
    )?;
    writeln!(out, "| --- | ---: | ---: | ---: | ---: | ---: | ---: |")?;
    for point in &with_memory {
        let start = point.memory_kib.first().map(|r| r.value).unwrap_or(0.0);
        let end = point.memory_kib.last().map(|r| r.value).unwrap_or(0.0);
        let peak = point
            .memory_kib
            .iter()
            .map(|r| r.value)
            .fold(f64::MIN, f64::max);
        let (per_session, fit) = match point.fit {
            // r² is printed beside the slope, never separately: a slope from a ramp that
            // is not linear has no single per-session meaning, and the reader needs both
            // numbers in the same glance to see that.
            Some(fit) => (
                format!("{:.1} KiB", fit.slope),
                format!("r²={:.3} over {} steps", fit.r2, fit.points),
            ),
            None => ("—".to_owned(), "—".to_owned()),
        };
        writeln!(
            out,
            "| {} | {start:.0} KiB | {peak:.0} KiB | {end:.0} KiB | {per_session} | {fit} | {} |",
            point.subject,
            point.memory_kib.len()
        )?;
    }
    writeln!(
        out,
        "\nNo allocator trim was forced for any subject. What a runtime returns after \
         deletes is its own policy — glibc on its threshold, Python only when an arena \
         empties, V8 when GC runs, Go on a scavenger timer — so the tail's shape is that \
         policy, and only the trend across repeats is a leak signal.\n"
    )?;
    Ok(())
}

fn optional(value: Option<f64>) -> String {
    // An em dash, not a zero: too few samples to support the percentile is a different
    // statement from "it was fast".
    value.map_or_else(|| "—".to_owned(), |value| format!("{value:.3}"))
}

fn describe_host(run: &Run) -> String {
    let mut parts = vec![run.host.label.clone()];
    if let Some(ec2) = &run.host.ec2 {
        parts.push(format!(
            "{} ({} capacity) in {}",
            ec2.instance_type, ec2.lifecycle, ec2.availability_zone
        ));
    }
    parts.push(format!("{} {}", run.host.os, run.host.arch));
    if let Some(kernel) = &run.host.kernel {
        parts.push(format!("kernel {kernel}"));
    }
    if let Some(thp) = &run.host.tuning.transparent_hugepages {
        parts.push(format!("THP {thp}"));
    }
    if let Some(cpus) = &run.host.tuning.subject_cpus {
        parts.push(format!("subject pinned to {cpus}"));
    }
    parts.join(", ")
}
