// Generated by tools/generate-component-contracts.py. Do not edit.

pub const AGENTLOOP_WORLD: &str = "aex:agentloop/agentloop@1.0.0";
pub const AGENTLOOP_CONTRACT_DIGEST: &str =
    "f50e756f5a363a3e686b504116a0ef64e3de83be30c2422595d1217fb23b3ff7";
pub const AGENTLOOP_WIT: &str = include_str!("../../../contracts/agentloop/v1/agentloop.wit");

pub const TOOL_WORLD: &str = "aex:tool/tool@1.0.0";
pub const TOOL_CONTRACT_DIGEST: &str =
    "c1434ba34caaedaedc9594e85be6ee0926475ecf2820a25d0e5522ec7d9f55c5";
pub const TOOL_WIT: &str = include_str!("../../../contracts/tool/v1/tool.wit");

pub const ENVIRONMENT_WORLD: &str = "aex:environment/environment@1.0.0";
pub const ENVIRONMENT_CONTRACT_DIGEST: &str =
    "8c00534afab60b5d95c2f9931bac7a27191657ffe6d193e6a7fa8bcd2a20aa1b";
pub const ENVIRONMENT_WIT: &str = include_str!("../../../contracts/environment/v1/environment.wit");

pub const MODEL_WORLD: &str = "aex:model/model@1.0.0";
pub const MODEL_CONTRACT_DIGEST: &str =
    "2c076c1b50c970dd95d178e4b91f6aff6f6559399b5f7a38f69f2b3290366123";
pub const MODEL_WIT: &str = include_str!("../../../contracts/model/v1/model.wit");
