// Generated by tools/generate-component-contracts.py. Do not edit.

pub const AGENTLOOP_WORLD: &str = "aex:agentloop/agentloop@1.0.0";
pub const AGENTLOOP_CONTRACT_DIGEST: &str =
    "f50e756f5a363a3e686b504116a0ef64e3de83be30c2422595d1217fb23b3ff7";
pub const AGENTLOOP_WIT: &str = include_str!("../../../contracts/agentloop/v1/agentloop.wit");

pub const TOOL_WORLD: &str = "aex:tool/tool@1.0.0";
pub const TOOL_CONTRACT_DIGEST: &str =
    "c1434ba34caaedaedc9594e85be6ee0926475ecf2820a25d0e5522ec7d9f55c5";
pub const TOOL_WIT: &str = include_str!("../../../contracts/tool/v1/tool.wit");

pub const ENVIRONMENT_WORLD: &str = "aex:environment/environment@1.0.0";
pub const ENVIRONMENT_CONTRACT_DIGEST: &str =
    "3a4e2c5510ac243a0111050daf2e0359afa9ab703edfd707c72518a954fcf1de";
pub const ENVIRONMENT_WIT: &str = include_str!("../../../contracts/environment/v1/environment.wit");

pub const MODEL_WORLD: &str = "aex:model/model@1.0.0";
pub const MODEL_CONTRACT_DIGEST: &str =
    "f5404825cf2efd4f8f756a47374e2be0dde6dec791c390663a54cd8029fe5376";
pub const MODEL_WIT: &str = include_str!("../../../contracts/model/v1/model.wit");
