// Generated by tools/generate-component-contracts.py. Do not edit.

pub const AGENTLOOP_WORLD: &str = "aex:agentloop/agentloop@1.0.0";
pub const AGENTLOOP_CONTRACT_DIGEST: &str =
    "f50e756f5a363a3e686b504116a0ef64e3de83be30c2422595d1217fb23b3ff7";
pub const AGENTLOOP_WIT: &str = include_str!("../../../contracts/agentloop/v1/agentloop.wit");

pub const TOOL_WORLD: &str = "aex:tool/tool@1.0.0";
pub const TOOL_CONTRACT_DIGEST: &str =
    "c393f26385d3e17632749313de01b15a827700eab592913a591b01795a5e99ff";
pub const TOOL_WIT: &str = include_str!("../../../contracts/tool/v1/tool.wit");

pub const ENVIRONMENT_WORLD: &str = "aex:environment/environment@1.0.0";
pub const ENVIRONMENT_CONTRACT_DIGEST: &str =
    "a7eb96d260d7a2470ea335242a846bd3ee43457641aeccefab77428c3631df08";
pub const ENVIRONMENT_WIT: &str = include_str!("../../../contracts/environment/v1/environment.wit");
