export { BrainClient as Brain, BrainClient, SessionHandle, Sessions } from "./client.js";
export type { BrainOptions, ResidentHostCredentials } from "./client.js";
export {
  agentloop,
  brainWasm,
  component,
  environment,
  inspectAgentloop,
  inspectComponent,
  inspectEnvironment,
  inspectPlacedTool,
  inspectResidentTool,
  tool,
} from "./extensions.js";
export type {
  AgentloopContract,
  BrainWasmOptions,
  EnvironmentContract,
  PlacedToolContract,
  ResidentToolContract,
  ToolRunContext,
} from "./extensions.js";
export { BrainError } from "./errors.js";
export type {
  AgentloopAdmission,
  AgentloopBinding,
  Component,
  CreateSessionOptions,
  CustomProviderModel,
  DomResource,
  Environment,
  FsResource,
  KnownProviderId,
  KnownProviderModel,
  ModelContentBlock,
  ModelMessage,
  ModelResponse,
  ModelSelection,
  ModelStopReason,
  ModelUsage,
  NetResource,
  OperationOptions,
  Outcome,
  ProcessResource,
  ResourceName,
  Resources,
  Schema,
  SchemaInput,
  SchemaOutput,
  SecretsResource,
  SessionEvent,
  SessionState,
  SessionStreamEvent,
  SessionTool,
  ToolBinding,
  ToolDefinition,
  VercelAiGatewayModel,
} from "./types.js";
