// Generated by tools/generate-contracts.py. Do not edit.

pub const AGENTLOOP_SCHEMA: &str = include_str!("../../../contracts/agentloop/v2/contract.json");
pub const AGENTLOOP_SCHEMA_DIGEST: &str =
    "b1feeb86805360aea644bfa713c420887b50dabbe74e7ebb60cf9996f3a9dc35";
pub const ENVIRONMENT_SCHEMA: &str = include_str!("../../../contracts/environment/v1/schemas.json");
pub const ENVIRONMENT_SCHEMA_DIGEST: &str =
    "9349e8d1aa91780718aadf31cc7f253391cad026729bba0e23c44e5f25d117c2";
pub const TOOL_SCHEMA: &str = include_str!("../../../contracts/tool/v1/schemas.json");
pub const TOOL_SCHEMA_DIGEST: &str =
    "b9110cf730c8a12ce59de55fbfd1e4e7fb492dac7912f72054d1f2e51d6494e7";
pub const SESSION_SCHEMA: &str = include_str!("../../../contracts/session/v1/schemas.json");
pub const SESSION_SCHEMA_DIGEST: &str =
    "f708aee0923347343856645e6e0f86e44075597cc2d65f3c0bb261481c574bb1";
pub const AGENTLOOP_WIT: &str = include_str!("../../../contracts/agentloop/v2/agentloop.wit");
pub const AGENTLOOP_WIT_DIGEST: &str =
    "c8e08980b89cdbec7ad89e870c5b9842caf5cb5a1f3b5c1a2eac0a9554e316d4";
pub const SESSION_OPENAPI: &str = include_str!("../../../contracts/session/v1/openapi.yaml");
pub const SESSION_OPENAPI_DIGEST: &str =
    "180d525df892d1938d60a95c4e163a6e56721eaac3ee2c0fe5d32f4db7f9891f";
