// Generated by tools/generate-contracts.py. Do not edit.

pub const AGENTLOOP_SCHEMA: &str = include_str!("../../../contracts/agentloop/v1/contract.json");
pub const AGENTLOOP_SCHEMA_DIGEST: &str =
    "246eba7ad006d9e1958cc20ad37aafb35d49fcfcc5276bd05e9e9f1d7f8c9079";
pub const ENVIRONMENT_SCHEMA: &str = include_str!("../../../contracts/environment/v2/schemas.json");
pub const ENVIRONMENT_SCHEMA_DIGEST: &str =
    "5b9c9ad65f5b0d1f5b18249fc69b018bc6a9496cba963ad7d25bc19eef6ac162";
pub const TOOL_SCHEMA: &str = include_str!("../../../contracts/tool/v1/schemas.json");
pub const TOOL_SCHEMA_DIGEST: &str =
    "11c2c2d8c42f56c0bf1bcaab45789dafbc508f539e556f23f68ad23e991bd0b8";
pub const SESSION_SCHEMA: &str = include_str!("../../../contracts/session/v1/schemas.json");
pub const SESSION_SCHEMA_DIGEST: &str =
    "2ba07db8c61884a5f1123f5aca69a0852d7439112fda8ed9ec02318ef7eef5a8";
pub const AGENTLOOP_WIT: &str = include_str!("../../../contracts/agentloop/v1/agentloop.wit");
pub const AGENTLOOP_WIT_DIGEST: &str =
    "4a1f2122cc626283dff08678b0144fbb26338dae371e2605d1238cc737f0c805";
pub const SESSION_OPENAPI: &str = include_str!("../../../contracts/session/v1/openapi.yaml");
pub const SESSION_OPENAPI_DIGEST: &str =
    "94b68983a4cc0e893570deff050f6f1114a04a148f76c8ff8fb6ce6a617cdf9d";
