#!/usr/bin/env python3
"""Generate stable identities and public views from the three canonical WIT worlds."""

from __future__ import annotations

import hashlib
import json
import pathlib
import re


ROOT = pathlib.Path(__file__).resolve().parents[1]
CONTRACTS = {
    "agentloop": ROOT / "contracts/agentloop/v1/agentloop.wit",
    "tool": ROOT / "contracts/tool/v1/tool.wit",
    "environment": ROOT / "contracts/environment/v1/environment.wit",
}
RUST_OUTPUT = ROOT / "crates/brain-component-host/src/generated.rs"
TYPESCRIPT_OUTPUT = ROOT / "packages/brain/src/generated/components.ts"
MANIFEST_OUTPUT = ROOT / "packages/brain/schemas/components.v1.json"
PACKAGE_CONTRACTS = ROOT / "packages/brain/contracts"


def normalized_bytes(path: pathlib.Path) -> bytes:
    return path.read_text(encoding="utf-8").replace("\r\n", "\n").encode("utf-8")


def contract(name: str, path: pathlib.Path) -> dict[str, str]:
    source = normalized_bytes(path).decode("utf-8")
    package_match = re.search(r"(?m)^package\s+([^;]+);$", source)
    world_match = re.search(rf"(?m)^world\s+{re.escape(name)}\s*{{", source)
    if package_match is None or world_match is None:
        raise RuntimeError(f"{path}: expected package and world {name!r}")
    package = package_match.group(1)
    namespace, version = package.rsplit("@", 1)
    return {
        "kind": name,
        "world": f"{namespace}/{name}@{version}",
        "digest": hashlib.sha256(normalized_bytes(path)).hexdigest(),
        "path": path.relative_to(ROOT).as_posix(),
    }


def rust_view(items: list[dict[str, str]]) -> str:
    lines = ["// Generated by tools/generate-component-contracts.py. Do not edit.", ""]
    for item in items:
        constant = item["kind"].upper()
        relative = "../../../" + item["path"]
        lines.extend(
            [
                f'pub const {constant}_WORLD: &str = "{item["world"]}";',
                f"pub const {constant}_CONTRACT_DIGEST: &str =",
                f'    "{item["digest"]}";',
                f'pub const {constant}_WIT: &str = include_str!("{relative}");',
                "",
            ]
        )
    return "\n".join(lines)


def typescript_view(items: list[dict[str, str]]) -> str:
    lines = ["// Generated by tools/generate-component-contracts.py. Do not edit.", ""]
    lines.append("export const componentContracts = {")
    for item in items:
        lines.append(
            f'  {item["kind"]}: {{ world: "{item["world"]}", digest: "{item["digest"]}" }},'
        )
    lines.extend(
        [
            "} as const;",
            "",
            "export type ComponentKind = keyof typeof componentContracts;",
            "export type ComponentWorld = (typeof componentContracts)[ComponentKind][\"world\"];",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    items = [contract(name, path) for name, path in CONTRACTS.items()]
    for item in items:
        path = CONTRACTS[item["kind"]].with_suffix(".digest")
        path.write_text(item["digest"] + "\n", encoding="ascii")
        package_path = PACKAGE_CONTRACTS / f'{item["kind"]}.wit'
        package_path.parent.mkdir(parents=True, exist_ok=True)
        package_path.write_bytes(normalized_bytes(CONTRACTS[item["kind"]]))
    RUST_OUTPUT.write_text(rust_view(items), encoding="utf-8", newline="\n")
    TYPESCRIPT_OUTPUT.write_text(typescript_view(items), encoding="utf-8", newline="\n")
    MANIFEST_OUTPUT.write_text(
        json.dumps({"version": 1, "contracts": items}, indent=2) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
