#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import json
import pathlib


ROOT = pathlib.Path(__file__).resolve().parents[1]
JSON_CONTRACTS = {
    "AGENTLOOP_SCHEMA": ROOT / "contracts/agentloop/v1/contract.json",
    "ENVIRONMENT_SCHEMA": ROOT / "contracts/environment/v1/schemas.json",
    "SESSION_SCHEMA": ROOT / "contracts/session/v1/schemas.json",
}
TEXT_CONTRACTS = {
    "AGENTLOOP_WIT": ROOT / "contracts/agentloop/v1/agentloop.wit",
    "SESSION_OPENAPI": ROOT / "contracts/session/v1/openapi.yaml",
}
RUST_OUTPUT = ROOT / "crates/brain-protocol/src/generated.rs"
TYPESCRIPT_OUTPUT = ROOT / "packages/brain-sdk/src/generated/contracts.ts"
PACKAGE_WIT_OUTPUT = ROOT / "packages/brain-sdk/contracts/agentloop.wit"


def canonical_json(path: pathlib.Path) -> bytes:
    value = json.loads(path.read_text(encoding="utf-8"))
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"), allow_nan=False).encode()


def normalized_text(path: pathlib.Path) -> bytes:
    return path.read_text(encoding="utf-8").replace("\r\n", "\n").encode()


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def main() -> None:
    values = {name: digest(canonical_json(path)) for name, path in JSON_CONTRACTS.items()}
    values.update({name: digest(normalized_text(path)) for name, path in TEXT_CONTRACTS.items()})

    rust = ["// Generated by tools/generate-contracts.py. Do not edit.", ""]
    for name, path in {**JSON_CONTRACTS, **TEXT_CONTRACTS}.items():
        relative = pathlib.Path("../../../") / path.relative_to(ROOT)
        rust.append(f'pub const {name}: &str = include_str!("{relative.as_posix()}");')
        rust.extend(
            [
                f"pub const {name}_DIGEST: &str =",
                f'    "{values[name]}";',
            ]
        )
    rust.append("")
    RUST_OUTPUT.write_text("\n".join(rust), encoding="utf-8", newline="\n")

    TYPESCRIPT_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    typescript = ["// Generated by tools/generate-contracts.py. Do not edit.", "", "export const contractDigests = {"]
    for name in sorted(values):
        typescript.append(f'  {name.lower()}: "{values[name]}",')
    typescript.extend(["} as const;", ""])
    TYPESCRIPT_OUTPUT.write_text("\n".join(typescript), encoding="utf-8", newline="\n")

    PACKAGE_WIT_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    PACKAGE_WIT_OUTPUT.write_bytes(normalized_text(TEXT_CONTRACTS["AGENTLOOP_WIT"]))

    (ROOT / "contracts/agentloop/v1/contract.digest").write_text(values["AGENTLOOP_SCHEMA"] + "\n", encoding="ascii")
    (ROOT / "contracts/agentloop/v1/agentloop.digest").write_text(values["AGENTLOOP_WIT"] + "\n", encoding="ascii")
    (ROOT / "contracts/environment/v1/contract.digest").write_text(values["ENVIRONMENT_SCHEMA"] + "\n", encoding="ascii")
    (ROOT / "contracts/session/v1/contract.digest").write_text(values["SESSION_SCHEMA"] + "\n", encoding="ascii")


if __name__ == "__main__":
    main()
